# Site settings
title: 宝宝周的博客
email: baobaozhou199606@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  raoul1996的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://raoul1996.github.io # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Raoul1996

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
twitter:
weibo:
github: raoul1996
instagram:
linkedin:

# avatar and Favicon
avatar: https://avatars0.githubusercontent.com/u/18366474?v=3&s=460
favicon: http://ohwxyjv7u.bkt.clouddn.com/favicon.ico

# disqus config
disqus:
  shortname: suyan-zh

# google analytics config
ga:
  id: UA-88776131-1
  url: raoul1996.github.io

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
 https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

